from app.domain.order import Order
from app.messages.requests.order_request_dto import OrderRequestDTO, ModifyOrderRequestDTO
from app.messages.responses.order_response_dto import OrderResponseDTO
from app.messages.responses.menu_item_response_dto import MenuItemResponseDTO  # New DTO for menu items
from datetime import datetime
from typing import List

def order_request_to_domain(dto: OrderRequestDTO) -> Order:
    """
    Converts an OrderRequestDTO to a domain Order object.
    Now supporting multiple menu items.
    """
    return Order(
        id=0,  # ID should be generated by the database
        customer_name=dto.customer_name,
        menu_items=dto.menu_items,  # List of menu item IDs
        quantity=dto.quantity,
        status="pending",
        order_time=datetime.now()
    )

def modify_order_dto_to_domain(dto: ModifyOrderRequestDTO, existing_order: Order) -> Order:
    """
    Updates an existing order with new menu items.
    """
    existing_order.menu_items = dto.menu_items  # Updating multiple menu items
    existing_order.quantity = dto.quantity
    return existing_order

def order_to_response(order: Order, message="Order placed successfully") -> OrderResponseDTO:
    """
    Converts a domain Order object to an OrderResponseDTO.
    """
    return OrderResponseDTO(
        order_id=order.id,
        customer_name=order.customer_name,
        menu_items=[MenuItemResponseDTO(menu_id=item.id, name=item.name, description=item.description, 
                                size=item.size, price=item.price) for item in order.menu_items],  # Convert menu items
        quantity=order.quantity,
        order_time=order.order_time.isoformat() if order.order_time else None,
        status=order.status,
        message=message
    )
